import '../models/hotel.dart';

final List<Hotel> allHotels = [
  // ASTANA
  Hotel(
    name: 'Rixos Astana',
    city: 'Astana',
    description: 'Роскошный отель в центре Астаны.',
    imagePath: 'assets/hotels2/hotel1.jpg',
    latitude: 51.128,
    longitude: 71.430,
  ),
  Hotel(
    name: 'Hilton Astana',
    city: 'Astana',
    description: 'Современный отель с бассейном и спа.',
    imagePath: 'assets/hotels2/hotel2.jpg',
    latitude: 51.134,
    longitude: 71.418,
  ),
  Hotel(
    name: 'Astana Plaza',
    city: 'Astana',
    description: 'Бюджетный отель с комфортными номерами.',
    imagePath: 'assets/hotels2/hotel5.jpg',
    latitude: 51.130,
    longitude: 71.440,
  ),
  Hotel(
    name: 'Hotel Nomad',
    city: 'Astana',
    description: 'Уютный бутик-отель в центре.',
    imagePath: 'assets/hotels2/hotel6.jpg',
    latitude: 51.125,
    longitude: 71.436,
  ),
  Hotel(
    name: 'Grand Park Hotel',
    city: 'Astana',
    description: 'Современный отель с рестораном.',
    imagePath: 'assets/hotels2/hotel7.jpg',
    latitude: 51.129,
    longitude: 71.428,
  ),

  // ALMATY
  Hotel(
    name: 'Ritz-Carlton Almaty',
    city: 'Almaty',
    description: '5-звёздочный отель с видом на горы.',
    imagePath: 'assets/hotels2/hotel3.jpg',
    latitude: 43.238,
    longitude: 76.945,
  ),
  Hotel(
    name: 'Holiday Inn Almaty',
    city: 'Almaty',
    description: 'Комфортный отель рядом с деловым центром.',
    imagePath: 'assets/hotels2/hotel8.jpg',
    latitude: 43.240,
    longitude: 76.946,
  ),
  Hotel(
    name: 'Almaty Hotel',
    city: 'Almaty',
    description: 'Классический отель в центре города.',
    imagePath: 'assets/hotels2/hotel9.jpg',
    latitude: 43.239,
    longitude: 76.947,
  ),
  Hotel(
    name: 'Hotel Kazakhstan',
    city: 'Almaty',
    description: 'Исторический отель с красивым видом.',
    imagePath: 'assets/hotels2/hotel10.jpg',
    latitude: 43.237,
    longitude: 76.950,
  ),
  Hotel(
    name: 'Mountain View Resort',
    city: 'Almaty',
    description: 'Отель в предгорьях с террасой.',
    imagePath: 'assets/hotels2/hotel11.jpg',
    latitude: 43.236,
    longitude: 76.943,
  ),

  // SHYMKENT
  Hotel(
    name: 'Shymkent Grand Hotel',
    city: 'Shymkent',
    description: 'Уютный отель в центре Шымкента.',
    imagePath: 'assets/hotels2/hotel4.jpg',
    latitude: 42.315,
    longitude: 69.596,
  ),
  Hotel(
    name: 'Canvas Hotel',
    city: 'Shymkent',
    description: 'Стильный отель с баром.',
    imagePath: 'assets/hotels2/hotel12.jpg',
    latitude: 42.316,
    longitude: 69.598,
  ),
  Hotel(
    name: 'Promenade Hotel',
    city: 'Shymkent',
    description: 'Современный отель с рестораном.',
    imagePath: 'assets/hotels2/hotel13.jpg',
    latitude: 42.314,
    longitude: 69.594,
  ),
  Hotel(
    name: 'Dostar Inn',
    city: 'Shymkent',
    description: 'Небольшой отель для деловых поездок.',
    imagePath: 'assets/hotels2/hotel14.jpg',
    latitude: 42.317,
    longitude: 69.595,
  ),
  Hotel(
    name: 'City Hotel Shymkent',
    city: 'Shymkent',
    description: 'Уютный семейный отель.',
    imagePath: 'assets/hotels2/hotel15.jpg',
    latitude: 42.318,
    longitude: 69.599,
  ),
];
